spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: url-manager
  application:
    name: url-shortener-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9000
  ssl:
    enabled: true
    key-store: classpath:microservice-keystore.jks
    key-store-password: ${KEY-STORE}
    key-alias: microservice


logging:
  level:
    root: INFO