global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'statistics-service'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
#    scheme: https
 #   tls_config:
  #    insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:9100"] 
