spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      routes:
        - id: url-management-service
          uri: ${URL_MANAGEMENT_SERVICE_URL}
          predicates:
            - Path=/url/management/**
            - Path=/api/short/url/**
          filters: []

server:
  port: 8080
  ssl:
    key-store: classpath:gateway-keystore.jks
    key-store-password: ${KEY_STORE}
    key-alias: gateway
