spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      routes:
        - id: url-shortener-service
          uri: ${URL_SHORTENER_SERVICE_URL}
          predicates:
            - Path=/url/management/**
          filters: []

server:
  port: 8080
  ssl:
    key-store: classpath:gateway-keystore.jks
    key-store-password: ${KEY-STORE}
    key-alias: gateway

logging:
  level:
    root: INFO
