spring:
  application:
    name: statistics-service

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 9100
  ssl:
    enabled: true
    key-store: classpath:statistics-keystore.jks
    key-store-password: ${KEY_STORE}
    key-alias: statistics