spring:
  application:
    name: statistics-service
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 9100
  ssl:
    enabled: true
    key-store: classpath:statistics-keystore.jks
    key-store-password: ${KEY-STORE}
    key-alias: statistics


logging:
  level:
    root: INFO