version: '3.7'
services:
  elasticsearch:
    build:
      context: .
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=FnK9l206ZbUaI3kxzJKo 
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=yourpassword
    volumes:
      - ./data:/usr/share/elasticsearch/data
